### ISSUE TITLE
Plug in not Responding/Also, question on how to grant sandbox access

### ISSUE THREAD

**Issue by monteros53** [latenitefilms/BRAWToolbox#182]
We're running 3 different Macs, FCP 10.8.1, library on an external disk, os 13.6.6, and 14.4.1
On each computer we get the plug in error, that BRAW Toolbox is not responding and will be disabled.  
1. Have restarted the computer
2. Uninstalled and reinstalled BRAW Toolbox
3. Deleted Final Cut Preferences
4. Tried relinking files

Other details, this is an FC Library that was copied onto a new disk, the files are stored in the Library and also another external. Tried linking from both. 
Your note on Collaboration and granting sandbox access; I don't have that window.  In the FC inspector, under Effects, there is no BRAW Toolbox.  So not sure how to get to 'Global Settings" and give sandbox access.
Hope you can help. We have a 30 minute film that we are trying to make small changes to for a festival in 6 days.

**Comment by latenitefilms** [comment]
Try this:

- Create a completely new library
- Create a new Project/Timeline
- Drag any Generator or Title to the timeline
- Apply the BRAW Toolbox effect to the Generator/Title
- In the Inspector you can now access **Global Settings** to **Grant Sandbox Access**.
- Added the drive that contains your footage
- Restart your computer
- Open your original library
- Assuming the files are all in the same location as they originally were (i.e. on the same external drive), everything should now work

<img width="2105" alt="image" src="https://github.com/user-attachments/assets/862f36ae-6879-47d6-9287-f1bf4b5e62d0">

This is explained in more detail here:

https://brawtoolbox.io/collaboration/

The BRAW Toolbox effect is applied INSIDE the Synchronised Clip (which is inside the Multicam Angle if you use Multicam clips). This is explained in more detail here: https://brawtoolbox.io/how-to-use/

If you're getting "plugin not responding" however, please send through your log files as explained here:

https://brawtoolbox.io/troubleshooting/#ive-run-into-a-bug-where-can-i-find-the-log-files

Hope this helps!

**Comment by monteros53** [comment]
Thanks, the instructions for granting sandbox access worked.  Still can't reconnect the files. I'm going to look into how to relink them manually. (105 clips)
However, I still have the plug-in not responding message.  Weird because I see it there and can open it....
M
________________________________

**Comment by latenitefilms** [comment]
Relinking media is explained in more detail here:

https://brawtoolbox.io/relinking/
